package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * Finestra principale dell'applicazione: menu di accesso ai quattro casi d'uso
 * implementati. È il punto di ingresso della GUI Swing.
 *
 * <p>La UI è definita nel file {@code FinestraPrincipale.form} (GUI Designer di
 * IntelliJ): i campi sotto sono agganciati per nome ai componenti del form.</p>
 */
public class FinestraPrincipale {

    private JPanel finestraPrincipalePanel;
    private JButton effettuaPrenotazioneButton;
    private JButton visualizzaDisponibilitaButton;
    private JButton elencoPrenotazioniButton;
    private JButton monitoraggioButton;

    // Riferimenti alle finestre aperte (per non duplicarle)
    private JFrame frameEffettuaPrenotazione;
    private JFrame frameVisualizzaDisponibilita;
    private JFrame frameElencoPrenotazioni;
    private JFrame frameMonitoraggio;

    public FinestraPrincipale() {
        effettuaPrenotazioneButton.addActionListener(e -> {
            if (nonVisibile(frameEffettuaPrenotazione)) {
                frameEffettuaPrenotazione = new FormEffettuaPrenotazione().apriFormEffettuaPrenotazione();
            } else {
                frameEffettuaPrenotazione.toFront();
            }
        });
        visualizzaDisponibilitaButton.addActionListener(e -> {
            if (nonVisibile(frameVisualizzaDisponibilita)) {
                frameVisualizzaDisponibilita = new FormVisualizzaDisponibilita().apriFormVisualizzaDisponibilita();
            } else {
                frameVisualizzaDisponibilita.toFront();
            }
        });
        elencoPrenotazioniButton.addActionListener(e -> {
            if (nonVisibile(frameElencoPrenotazioni)) {
                frameElencoPrenotazioni = new FormElencoPrenotazioniMedico().apriFormElencoPrenotazioniMedico();
            } else {
                frameElencoPrenotazioni.toFront();
            }
        });
        monitoraggioButton.addActionListener(e -> {
            if (nonVisibile(frameMonitoraggio)) {
                frameMonitoraggio = new FormMonitoraggio().apriFormMonitoraggio();
            } else {
                frameMonitoraggio.toFront();
            }
        });
    }

    private boolean nonVisibile(JFrame frame) {
        return frame == null || !frame.isDisplayable();
    }

    /**
     * Crea e mostra la finestra principale. Restituisce il {@link JFrame} creato.
     */
    public JFrame apriFinestraPrincipale() {
        JFrame frame = new JFrame("Ambulatorio Medico");
        frame.setContentPane(finestraPrincipalePanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        finestraPrincipalePanel = new JPanel();
        finestraPrincipalePanel.setLayout(new GridLayoutManager(2, 1, new Insets(20, 20, 20, 20), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        finestraPrincipalePanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Gestione Ambulatorio Medico");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        finestraPrincipalePanel.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        visualizzaDisponibilitaButton = new JButton();
        visualizzaDisponibilitaButton.setText("visualizza disponibilità");
        panel2.add(visualizzaDisponibilitaButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        monitoraggioButton = new JButton();
        monitoraggioButton.setText("monitoraggio ambulatorio");
        panel2.add(monitoraggioButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        effettuaPrenotazioneButton = new JButton();
        effettuaPrenotazioneButton.setText("effettua prenotazione");
        panel2.add(effettuaPrenotazioneButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        elencoPrenotazioniButton = new JButton();
        elencoPrenotazioniButton.setText("elenco prenotazioni");
        panel2.add(elencoPrenotazioniButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return finestraPrincipalePanel;
    }
}
