package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.toedter.calendar.JDateChooser;
import controller.ControllerPrenotazioni;

import javax.swing.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

/**
 * Boundary del caso d'uso "Visualizza disponibilità".
 * L'utente sceglie una specializzazione, un medico associato e una data;
 * il sistema mostra le fasce orarie libere di quel medico.
 *
 * <p>La UI è definita in {@code FormVisualizzaDisponibilita.form}. La boundary
 * comunica solo con il {@link ControllerPrenotazioni} e riceve dati come
 * stringhe: non importa mai il package {@code entity}.</p>
 */
public class FormVisualizzaDisponibilita {

    private JPanel visualizzaDisponibilitaPanel;
    private JComboBox comboMedico;
    private JDateChooser selettoreData;
    private JButton mostraButton;
    private JList listaFasce;
    private JComboBox comboSpecializzazione;
    private JLabel labelEsito;

    private final ControllerPrenotazioni controller = ControllerPrenotazioni.getInstance();
    private final SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    private final DefaultListModel<String> modelloFasce = new DefaultListModel<>();

    /**
     * Medici correnti della specializzazione selezionata: coppie {email, nome}.
     */
    private List<String[]> mediciCorrenti = new ArrayList<>();

    public FormVisualizzaDisponibilita() {
        //$$$setupUI$$$();
        $$$setupUI$$$();
        listaFasce.setModel(modelloFasce);

        for (String descrizione : controller.getSpecializzazioni()) {
            comboSpecializzazione.addItem(descrizione);
        }
        comboSpecializzazione.setSelectedIndex(-1);

        comboSpecializzazione.addActionListener(e -> aggiornaMedici());
        mostraButton.addActionListener(e -> mostraDisponibilita());
    }

    private void aggiornaMedici() {
        comboMedico.removeAllItems();
        String specializzazione = (String) comboSpecializzazione.getSelectedItem();
        if (specializzazione == null) {
            mediciCorrenti = new ArrayList<>();
            return;
        }
        mediciCorrenti = controller.getMedici(specializzazione);
        for (String[] medico : mediciCorrenti) {
            comboMedico.addItem(medico[1]);
        }
    }

    private void mostraDisponibilita() {
        modelloFasce.clear();
        labelEsito.setText(" ");

        int indice = comboMedico.getSelectedIndex();
        if (indice < 0 || indice >= mediciCorrenti.size() || selettoreData.getDate() == null) {
            JOptionPane.showMessageDialog(visualizzaDisponibilitaPanel, "Seleziona medico e data.",
                    "Dati mancanti", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String emailMedico = mediciCorrenti.get(indice)[0];
        String data = formato.format(selettoreData.getDate());
        String[] fasce = controller.visualizzaDisponibilita(emailMedico, data);

        if (fasce.length == 0) {
            labelEsito.setText("  Nessuna fascia disponibile per il " + data + ".");
            return;
        }
        for (String fascia : fasce) {
            modelloFasce.addElement(fascia);
        }
        labelEsito.setText("  " + fasce.length + " fasce libere il " + data + ".");
    }

    /**
     * Componente a creazione manuale richiesto dal form (custom-create).
     */
    private void createUIComponents() {
        selettoreData = new JDateChooser();
    }

    /**
     * Crea e mostra la finestra del caso d'uso. Restituisce il {@link JFrame} creato.
     */
    public JFrame apriFormVisualizzaDisponibilita() {
        JFrame frame = new JFrame("Visualizza disponibilità");
        frame.setContentPane(visualizzaDisponibilitaPanel);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        visualizzaDisponibilitaPanel = new JPanel();
        visualizzaDisponibilitaPanel.setLayout(new GridLayoutManager(6, 2, new Insets(20, 20, 20, 20), -1, -1));
        visualizzaDisponibilitaPanel.setPreferredSize(new Dimension(650, 350));
        final JLabel label1 = new JLabel();
        label1.setText("Specializzazione");
        visualizzaDisponibilitaPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Medico");
        visualizzaDisponibilitaPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Data");
        visualizzaDisponibilitaPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comboMedico = new JComboBox();
        visualizzaDisponibilitaPanel.add(comboMedico, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        visualizzaDisponibilitaPanel.add(selettoreData, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(120, 20), null, null, 0, false));
        mostraButton = new JButton();
        mostraButton.setText("Mostra disponibilità");
        visualizzaDisponibilitaPanel.add(mostraButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        listaFasce = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        listaFasce.setModel(defaultListModel1);
        visualizzaDisponibilitaPanel.add(listaFasce, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        labelEsito = new JLabel();
        labelEsito.setText("Label");
        visualizzaDisponibilitaPanel.add(labelEsito, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comboSpecializzazione = new JComboBox();
        visualizzaDisponibilitaPanel.add(comboSpecializzazione, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return visualizzaDisponibilitaPanel;
    }
}
