package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.toedter.calendar.JDateChooser;
import controller.ControllerPrenotazioni;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Map;

/**
 * Boundary del caso d'uso "Monitoraggio ambulatorio" (amministratore).
 * Mostra, per un intervallo di tempo: numero di visite prenotate, numero di
 * annullamenti, distribuzione per specializzazione e occupazione delle fasce orarie.
 *
 * <p>La UI è definita in {@code FormMonitoraggio.form}. La boundary comunica solo
 * con il {@link ControllerPrenotazioni} e riceve il riepilogo come mappa di
 * stringhe: non importa mai il package {@code entity}.</p>
 */
public class FormMonitoraggio {

    private JPanel monitoraggioPanel;
    private JDateChooser dataInizio;
    private JDateChooser dataFine;
    private JButton generaButton;
    private JLabel etichettaTotali;
    private JTable tabellaSpec;
    private JTable tabellaFasce;

    private final ControllerPrenotazioni controller = ControllerPrenotazioni.getInstance();
    private final SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

    private final DefaultTableModel modelloSpec = new DefaultTableModel(
            new Object[]{"Specializzazione", "Prenotazioni"}, 0);
    private final DefaultTableModel modelloFasce = new DefaultTableModel(
            new Object[]{"Fascia oraria", "Occupazione"}, 0);

    public FormMonitoraggio() {
        //$$$setupUI$$$();
        $$$setupUI$$$();
        tabellaSpec.setModel(modelloSpec);
        tabellaSpec.getTableHeader().setReorderingAllowed(false);
        tabellaFasce.setModel(modelloFasce);
        tabellaFasce.getTableHeader().setReorderingAllowed(false);

        generaButton.addActionListener(e -> generaReport());
    }

    private void generaReport() {
        if (dataInizio.getDate() == null || dataFine.getDate() == null) {
            JOptionPane.showMessageDialog(monitoraggioPanel, "Seleziona l'intervallo di date.",
                    "Dati mancanti", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String inizio = formato.format(dataInizio.getDate());
        String fine = formato.format(dataFine.getDate());
        if (inizio.compareTo(fine) > 0) {
            JOptionPane.showMessageDialog(monitoraggioPanel, "La data iniziale è successiva a quella finale.",
                    "Intervallo non valido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Map<String, List<String[]>> riepilogo =
                controller.visualizzaMonitoraggioAmbulatorio(inizio, fine);

        String[] totali = riepilogo.get("totali").get(0);
        etichettaTotali.setText(String.format(
                "Visite prenotate: %s    |    Annullamenti: %s    (%s → %s)",
                totali[0], totali[1], inizio, fine));

        modelloSpec.setRowCount(0);
        for (String[] riga : riepilogo.get("specializzazioni")) {
            modelloSpec.addRow(riga);
        }
        if (modelloSpec.getRowCount() == 0) {
            modelloSpec.addRow(new Object[]{"(nessuna prenotazione)", "0"});
        }

        modelloFasce.setRowCount(0);
        for (String[] riga : riepilogo.get("fasce")) {
            modelloFasce.addRow(riga);
        }
    }

    /**
     * Componenti a creazione manuale richiesti dal form (custom-create).
     */
    private void createUIComponents() {
        dataInizio = new JDateChooser();
        dataFine = new JDateChooser();
    }

    /**
     * Crea e mostra la finestra del caso d'uso. Restituisce il {@link JFrame} creato.
     */
    public JFrame apriFormMonitoraggio() {
        JFrame frame = new JFrame("Monitoraggio ambulatorio");
        frame.setContentPane(monitoraggioPanel);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        monitoraggioPanel = new JPanel();
        monitoraggioPanel.setLayout(new GridLayoutManager(7, 2, new Insets(20, 20, 20, 20), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 5, new Insets(0, 0, 0, 0), -1, -1));
        monitoraggioPanel.add(panel1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Dal:");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel1.add(dataInizio, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Al:");
        panel1.add(label2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel1.add(dataFine, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        monitoraggioPanel.add(spacer2, new GridConstraints(3, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        generaButton = new JButton();
        generaButton.setText("genera report");
        monitoraggioPanel.add(generaButton, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Prenotazioni per specializzazione:");
        monitoraggioPanel.add(label3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tabellaSpec = new JTable();
        monitoraggioPanel.add(tabellaSpec, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Occupazione fasce orarie:");
        monitoraggioPanel.add(label4, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tabellaFasce = new JTable();
        monitoraggioPanel.add(tabellaFasce, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        etichettaTotali = new JLabel();
        etichettaTotali.setText("");
        monitoraggioPanel.add(etichettaTotali, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return monitoraggioPanel;
    }
}
